name: CI-CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt
      - run: pytest

      - name: Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hello-mlops-app:${{ github.run_number }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-mlops-app:${{ github.run_number }}

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Staging Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ajay-mlops-webapp-docker-acr
          images: ${{ secrets.ACR_LOGIN_SERVER }}/hello-mlops-app:${{ github.run_number }}
          publish-profile: ${{ secrets.STAGING_PUBLISH_PROFILE }}

  deploy-production:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ajay-mlops-prod
          images: ${{ secrets.ACR_LOGIN_SERVER }}/hello-mlops-app:${{ github.run_number }}
          publish-profile: ${{ secrets.PROD_PUBLISH_PROFILE }}