name: CI-Staging

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt
      - run: pytest

      - name: Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hello-mlops-app:${{ github.run_number }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-mlops-app:${{ github.run_number }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Staging
        run: |
          az webapp config container set \
            --name ajay-mlops-webapp-docker-acr \
            --resource-group rg-mlops-demo \
            --container-image-name ${{ secrets.ACR_LOGIN_SERVER }}/hello-mlops-app:${{ github.run_number }} \
            --container-registry-url https://${{ secrets.ACR_LOGIN_SERVER }} \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

          az webapp restart \
            --name ajay-mlops-webapp-docker-acr \
            --resource-group rg-mlops-demo